### ISSUE TITLE
Update LICENSE

### ISSUE THREAD

**Issue by mwakok** [leilaicruz/LaanLab-SATAY-DataAnalysis#46]
The repository makes use of two different licenses, namely Apache 2.0 and BSD

**Comment by leilaicruz** [comment]
I thought we changed to Apache 2.0 , how can we remove the other one?

**Comment by leilaicruz** [comment]
I changed in the master branch to Apache 2.0 :)

**Comment by mwakok** [comment]
I have also updated the copyright holder.
